kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sfsturbo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: sfsturbo.csi.huaweicloud.com
